# Generated by Django 4.2 on 2024-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
